version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: golang:1.12.4-stretch
    working_directory: /go/src/github.com/SmallBusinessVictoria-ABR-ETL/abr-etl
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true

      - add_ssh_keys:
          fingerprints:
            - "de:52:29:cc:69:60:a3:8c:fd:fa:fa:12:2c:f6:91:b9"

      - run: go get -d
      - run: mkdir -p build
      - run: GOOS=linux GOARCH=amd64 go build -o build/abr-etl abr-etl.go

      - run: cp abr-etl.sh build
      - aws-cli/install:
      - run: aws s3 sync build/ s3://sbv-abr-etl/code/

